### ISSUE TITLE
pip install keras-tuner modifies underlying tensorflow version, breaks default AWS EC2 GPU instance

### ISSUE THREAD

**Issue by spencerfrei** [keras-team/keras-tuner#194]
I would like to user Keras Tuner to optimize hyperparameters on a model using a GPU EC2 (p2) instance on AWS.  The Ubuntu Deep Learning AMI on AWS (Ubuntu 16.04 Version 26.0 - ami-07728e9e2742b0662) comes with a conda environment that has TF 2.0.0 installed.  And from my understanding, keras tuner should work for any TF version >= 2.0.0.  However, when trying to use pip to install keras tuner, the installation re-installs TF 2.1.0-rc1, which is not desirable behavior.  In fact, something ends up breaking (one gets the error "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize...") which I believe is due to the new installation not correctly setting up the CUDA + TF + GPU communication pathways.

Per the suggested steps [in the other issue that might be related to this](https://github.com/keras-team/keras-tuner/issues/168#issuecomment-554044407), I have tried various sequences of in/uninstalling keras-tuner, in/uninstalling tensorflow, and in any sequence of installation and uninstallation of each option it results in the same breaking.  Regardless, I think it is undesirable behavior for keras tuner to change the TF version upon installation, especially given that this behavior prevents the ability to use keras tuner out of the box on the default AWS GPU EC2 instance.

Is there a way to ensure that the installation of keras tuner via pip does not modify the TF version?  As far as I can tell, this is not spelled out in any of the documentation.

# Steps to reproduce the error:
    # open up a p2.large instance on AWS
    source activate tensorflow2_p36
    python -c 'import tensorflow as tf; print(tf.__version__)' 
    # returns 2.0.0
    pip install keras-tuner
    python -c 'import tensorflow as tf; print(tf.__version__)'
    # returns 2.1.0-rc1

Surprisingly, I have tried this on my local machine, and the above does not occur.  Namely, if I do:

    pip install tensorflow --user
    python -c 'import tensorflow as tf; print(tf.__version__)' 
    # returns 2.0.0
    pip install keras-tuner
    python -c 'import tensorflow as tf; print(tf.__version__)'
    # returns 2.0.0

I'm confused as to what is going on.

**Comment by BDANG** [comment]
My current fix:

Install `keras-tuner's` dependencies:

```
terminaltables==3.1.0
tabulate==0.8.6
tqdm==4.41.1
colorama==0.4.3
```

Then install keras-tuner with:

`pip install -U --no-deps keras-tuner`

---
I dont know if there's a pip flag to ignore specific dependencies. But it is how I solved my custom Docker image based on `tensorflow/tensorflow:latest-gpu-jupyter` (GPU-enabled TensorFlow 2.0)

This is what my `Dockerfile` looks like if you were curious

```
FROM tensorflow/tensorflow:latest-gpu-py3-jupyter

### Copy local files into the docker-image ###
# additional python modules required for project
COPY requirements.txt /tf/requirements.txt

# additional setup file for installing my source code as a python library
COPY setup.py /tf/setup.py

# source code (acts as a python library in my use case)
COPY <directory-with-source-code> /tf/<directory-with-source-code>

# starting the docker container will place you in the working directory /tf
WORKDIR /tf

# install python modules (i.e. terminaltables, etc)
RUN pip install -r requirements.txt

# install keras-tuner without upgrading tensorflow module
RUN pip install -U --no-deps keras-tuner==1.0.0

# install my source code as a python module
RUN pip install -e .
```

**Comment by omalleyt12** [comment]
@spencerfrei Thanks for the issue!

I'm working on releasing a new minor version to pypi to fix this, will ping this thread when it is up

**Comment by spencerfrei** [comment]
> My current fix:
> 
> Install `keras-tuner's` dependencies:
> 
> ```
> terminaltables==3.1.0
> tabulate==0.8.6
> tqdm==4.41.1
> colorama==0.4.3
> ```
> 
> Then install keras-tuner with:
> 
> `pip install -U --no-deps keras-tuner`
> 
> I dont know if there's a pip flag to ignore specific dependencies. But it is how I solved my custom Docker image based on `tensorflow/tensorflow:latest-gpu-jupyter` (GPU-enabled TensorFlow 2.0)
> 
> This is what my `Dockerfile` looks like if you were curious
> 
> ```
> FROM tensorflow/tensorflow:latest-gpu-py3-jupyter
> 
> ### Copy local files into the docker-image ###
> # additional python modules required for project
> COPY requirements.txt /tf/requirements.txt
> 
> # additional setup file for installing my source code as a python library
> COPY setup.py /tf/setup.py
> 
> # source code (acts as a python library in my use case)
> COPY <directory-with-source-code> /tf/<directory-with-source-code>
> 
> # starting the docker container will place you in the working directory /tf
> WORKDIR /tf
> 
> # install python modules (i.e. terminaltables, etc)
> RUN pip install -r requirements.txt
> 
> # install keras-tuner without upgrading tensorflow module
> RUN pip install -U --no-deps keras-tuner==1.0.0
> 
> # install my source code as a python module
> RUN pip install -e .
> ```

This worked for me, thanks!

**Comment by henrypinkard** [comment]
+1 to this issue. I've run into the same thing using TF2.0 images on Google Cloud Platform, except for me, I'm able to get keras_tuner working, but it does everything on the CPU instead of GPU. As far as I can tell, it is installing a CPU version of TF alongside the GPU version, which is causing the problem. This seems to happen even when I upgrade to the tensorflow-gpu2.1.0rc2

**Comment by omalleyt12** [comment]
I just uploaded a new release on PyPI, version 1.0.1, to fix this. Keras Tuner doesn't explicitly depend on TensorFlow now, so you'll have to make sure TensorFlow is installed separately:

https://pypi.org/project/keras-tuner/

Please let me know and reopen if you're still running into any issues
